name: C++ Lint Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Run clang-format check
        run: |
          FILES=$(find . -type f \( -name "*.cpp" -o -name "*.h" \))
          echo "Running clang-format on the following files:"
          echo "$FILES"
          echo "$FILES" | xargs clang-format --dry-run --Werror

      - name: Run clang-tidy check
        run: |
          FILES=$(find . -type f -name "*.cpp")
          echo "Running clang-tidy on the following files:"
          echo "$FILES"
          for file in $FILES; do
            clang-tidy "$file" -- -I.
          done
